FROM mcr.microsoft.com/dotnet/framework:4.7.2 AS build
WORKDIR /app
COPY WcfClient/. .
RUN msbuild /p:Configuration=Release

FROM mcr.microsoft.com/dotnet/framework:4.7.2 AS runtime
WORKDIR /app
COPY --from=build /app/bin/Release .
ENTRYPOINT WcfClient.exe